### ISSUE TITLE
ERROR: in mclapply()

### ISSUE THREAD

**Issue by scrameri** [knausb/vcfR_win-builder#1]
Hi Brian,
Sorry for bothering again with windows related problems... I've just tried to convert a vcfR object {vcfR} into a genlight object {adegenet} because I'd like to see the Principal Components of the filtered SNP dataset (a PCA can be done with genlight objects using glPca(). At some point, the function vcfR2genlight() calls mclapply(), which does not work on windows (since it relies on forking). Is there a way around this? 

``` r
> vcf <- read.vcf("FilteredSNPs.vcf")
> dd <- vcfR2genlight(vcf)
Error in mclapply(1:nrow(input$gen), function(i) new("SNPbin", as.integer(input$gen[i,  : 
  'mc.cores' > 1 is not supported on Windows
```

**Comment by knausb** [comment]
Hi Simon,

My code does not use mclapply directly. Your problem is perhaps one of the reasons I'm afraid of it:) My function vcfR2genlight calls adegenet::as.genlight to create the genelight object. I'm going to guess that this is what is calling mclapply. A little Googling found this:

http://lists.r-forge.r-project.org/pipermail/adegenet-forum/2013-July/000681.html

Although I'm not sure its a very elegant solution. You might be able to get away with simply setting:

options(mc.cores = 1)

But you'll have to use that as part of every session where you call mclapply. As you may have realized, mclapply will never provide parallelization on Windows because it relies on forks. I sort of get the feeling the R folks are still working on a good way to support parallelization that will work on all platforms.

Let me know if either of those work. If setting options works for you it could be something for me to incorporate into my vcfR2genlight function and perhaps help a few Windows users.

Good luck!
Brian

**Comment by scrameri** [comment]
Hi Brian,
neither of both workarounds do the trick:

setting mc.cores options to 1

``` r
> getOption("mc.cores")
NULL
> options(mc.cores = 1)
> getOption("mc.cores")
[1] 1
> dd <- vcfR2genlight(vcf)
Loading required package: parallel
Error in mclapply(1:nrow(input$gen), function(i) new("SNPbin", as.integer(input$gen[i,  : 
  'mc.cores' > 1 is not supported on Windows
```

hacking mclapply() function

``` r
> require(parallel)
Loading required package: parallel
> getOption("mc.cores")
NULL
> print(mclapply)
function (X, FUN, ..., mc.preschedule = TRUE, mc.set.seed = TRUE, 
    mc.silent = FALSE, mc.cores = 1L, mc.cleanup = TRUE, mc.allow.recursive = TRUE) 
{
    cores <- as.integer(mc.cores)
    if (cores < 1L) 
        stop("'mc.cores' must be >= 1")
    if (cores > 1L) 
        stop("'mc.cores' > 1 is not supported on Windows")
    lapply(X, FUN, ...)
}
<bytecode: 0x000000000b392ce8>
<environment: namespace:parallel>
> 
> mclapply <- function (X, FUN, ..., mc.preschedule = TRUE, mc.set.seed = TRUE, 
+                               mc.silent = FALSE, mc.cores = 1L, mc.cleanup = TRUE, mc.allow.recursive = TRUE) 
+ {
+    cores <- as.integer(mc.cores)
+    if (cores < 1L) 
+      stop("'mc.cores' must be >= 1")
+    if (cores > 1L) 
+    lapply(X, FUN, ...)
+ }
> print(mclapply)
function (X, FUN, ..., mc.preschedule = TRUE, mc.set.seed = TRUE, 
                              mc.silent = FALSE, mc.cores = 1L, mc.cleanup = TRUE, mc.allow.recursive = TRUE) 
{
   cores <- as.integer(mc.cores)
   if (cores < 1L) 
     stop("'mc.cores' must be >= 1")
   if (cores > 1L) 
   lapply(X, FUN, ...)
}
> dd <- vcfR2genlight(vcf)
Error in mclapply(1:nrow(input$gen), function(i) new("SNPbin", as.integer(input$gen[i,  : 
  'mc.cores' > 1 is not supported on Windows
```

Combined approach:

``` r
> require(parallel)
Loading required package: parallel
> getOption("mc.cores")
NULL
> options(mc.cores = 1)
> getOption("mc.cores")
[1] 1
> print(mclapply)
function (X, FUN, ..., mc.preschedule = TRUE, mc.set.seed = TRUE, 
    mc.silent = FALSE, mc.cores = 1L, mc.cleanup = TRUE, mc.allow.recursive = TRUE) 
{
    cores <- as.integer(mc.cores)
    if (cores < 1L) 
        stop("'mc.cores' must be >= 1")
    if (cores > 1L) 
        stop("'mc.cores' > 1 is not supported on Windows")
    lapply(X, FUN, ...)
}
<bytecode: 0x0000000039d5af78>
<environment: namespace:parallel>
> 
> mclapply <- function (X, FUN, ..., mc.preschedule = TRUE, mc.set.seed = TRUE, 
+                               mc.silent = FALSE, mc.cores = 1L, mc.cleanup = TRUE, mc.allow.recursive = TRUE) 
+ {
+    cores <- as.integer(mc.cores)
+    if (cores < 1L) 
+      stop("'mc.cores' must be >= 1")
+    if (cores > 1L) 
+    lapply(X, FUN, ...)
+ }
> print(mclapply)
function (X, FUN, ..., mc.preschedule = TRUE, mc.set.seed = TRUE, 
                              mc.silent = FALSE, mc.cores = 1L, mc.cleanup = TRUE, mc.allow.recursive = TRUE) 
{
   cores <- as.integer(mc.cores)
   if (cores < 1L) 
     stop("'mc.cores' must be >= 1")
   if (cores > 1L) 
   lapply(X, FUN, ...)
}
> dd <- vcfR2genlight(vcf)
Error in mclapply(1:nrow(input$gen), function(i) new("SNPbin", as.integer(input$gen[i,  : 
  'mc.cores' > 1 is not supported on Windows
```

**Comment by knausb** [comment]
Hi Simon,

I'm afraid I haven't been able to come up with a solution. I think what needs to happen is that mclapply needs to be told mc.cores = 1. But because it is adegenet code that is calling mclapply I have little control over it.  I have raised an issue on the adegenet site:

https://github.com/thibautjombart/adegenet/issues/109

We'll see if we can come up with something.

Thanks!
Brian

**Comment by scrameri** [comment]
great, adegenet users may also want to have this sorted out.

**Comment by knausb** [comment]
Hi Simon,

Thibaut has asked me to fork and make a pull request. I've forked adegenet to make my own copy. I've made the changes I proposed. It built in Linux (but we sort of knew that would work, just means I probably didn't break anything). And I've just tried it on a colleague's Windows box, and it worked. Now, I'm asking you for a favor. I've placed a compiled binary of my version of adegenet at my win-builder repo:

https://github.com/knausb/vcfR_win-builder

The warning doesn't apply to you. That version of adegenet is for you.  Could you install it and let me know if it works? If it does, we'll make a pull request to the adegenet people and see if they like it.

Thanks and good luck!
Brian

**Comment by scrameri** [comment]
Hi Brian,

``` r
> install.packages("adegenet_2.0.1.zip",repos=NULL)
package ‘adegenet’ successfully unpacked and MD5 sums checked
> require("adegenet")
Loading required package: adegenet
Loading required package: ade4
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘vegan’
> install.packages("vegan")
also installing the dependency ‘permute’

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/permute_0.8-4.zip'
Content type 'application/zip' length 501701 bytes (489 KB)
downloaded 489 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/vegan_2.3-1.zip'
Content type 'application/zip' length 2874588 bytes (2.7 MB)
downloaded 2.7 MB

package ‘permute’ successfully unpacked and MD5 sums checked
package ‘vegan’ successfully unpacked and MD5 sums checked

> require(vcfR)
Loading required package: vcfR
> dd <- vcfR2genlight(vcf)
Loading required package: parallel
> dd
 /// GENLIGHT OBJECT /////////

 // 26 genotypes,  198,411 binary SNPs, size: 5.9 Mb
 297323 (5.76 %) missing data

 // Basic content
   @gen: list of 26 SNPbin

 // Optional content
   @ind.names:  26 individual labels
   @loc.names:  198411 locus labels
   @chromosome: factor storing chromosomes of the SNPs
   @position: integer storing positions of the SNPs
   @other: a list containing: elements without names 
```

it works! I only lacked vegan package :)

**Comment by knausb** [comment]
Yay! These work around installs tend to miss dependencies which are automated when you install from CRAN. I've spent some time doing what you had to do with vegan on a colleague's computer today.  But it sounds like it works! Congratulations and thank you! I will post the pull request and we may see this in the next adegenet.

Brian

**Comment by knausb** [comment]
Hi Simon, my pull request has now been merged with the GitHub version of adegenet. You should now be able to install the GitHub version of adegenet and it should work like the one I provided through win-builder.

Thank you and good luck!
Brian
